[project]
authors = ["Thomas Hartmann <thomas.hartmann@th-ht.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "sci_other_predictive_activity"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
mne = ">=1.8.0,<2"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.9.2,<4"
scikit-learn = ">=1.5.2,<2"
scipy = ">=1.14.1,<2"
tqdm = ">=4.66.5,<5"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
quarto = ">=1.5.57,<2"
r-expm = ">=1.0_0,<2"
r-patchwork = ">=1.3.0,<2"
r-magrittr = ">=2.0.3,<3"
r-tictoc = ">=1.2.1,<2"
r-correlation = ">=0.8.5,<0.9"
r-abind = ">=1.4_5,<2"
r-tidyverse = ">=2.0.0,<3"
r-reticulate = ">=1.39.0,<2"
plus_sync = ">=0.7.0,<0.8"
plus_slurm = ">=0.3.2,<0.4"
r-pals = ">=1.9,<2"
r-scales = ">=1.3.0,<2"
r-languageserver = ">=0.3.16,<0.4"
radian = ">=0.6.13,<0.7"
r-httpgd = ">=1.3.1,<2"
